/**
 * CLI error codes
 */
export const CLI_ERROR_CODES = {
  // Init errors (E001-E009)
  INIT_DIR_EXISTS: "CLI_E001",
  INIT_BUN_NOT_FOUND: "CLI_E002",
  INIT_TEMPLATE_NOT_FOUND: "CLI_E003",

  // Dev errors (E010-E019)
  DEV_PORT_IN_USE: "CLI_E010",
  DEV_MANIFEST_NOT_FOUND: "CLI_E011",
  DEV_NO_ROUTES: "CLI_E012",

  // Guard errors (E020-E029)
  GUARD_CONFIG_INVALID: "CLI_E020",
  GUARD_PRESET_NOT_FOUND: "CLI_E021",
  GUARD_VIOLATION_FOUND: "CLI_E022",

  // Build errors (E030-E039)
  BUILD_ENTRY_NOT_FOUND: "CLI_E030",
  BUILD_BUNDLE_FAILED: "CLI_E031",
  BUILD_OUTDIR_NOT_WRITABLE: "CLI_E032",

  // Config errors (E040-E049)
  CONFIG_PARSE_FAILED: "CLI_E040",
  CONFIG_VALIDATION_FAILED: "CLI_E041",

  // Test errors (E060-E069) — Phase 12.1
  TEST_NO_MATCH: "CLI_E060",
  TEST_RUNNER_FAILED: "CLI_E061",
  TEST_UNKNOWN_TARGET: "CLI_E062",

  // CLI usage errors (E100+)
  UNKNOWN_COMMAND: "CLI_E100",
  UNKNOWN_SUBCOMMAND: "CLI_E101",
  MISSING_ARGUMENT: "CLI_E102",

  // Deploy errors (E200-E229) — Phase 13.1
  DEPLOY_UNSUPPORTED_TARGET: "CLI_E200",
  DEPLOY_CONFIG_INVALID: "CLI_E201",
  DEPLOY_BUILD_FAILED: "CLI_E202",
  DEPLOY_GUARD_FAILED: "CLI_E203",
  DEPLOY_ARTIFACT_WRITE_FAILED: "CLI_E204",
  DEPLOY_PROVIDER_CLI_MISSING: "CLI_E205",
  DEPLOY_PROVIDER_CLI_OUTDATED: "CLI_E206",
  DEPLOY_SECRET_MISSING: "CLI_E207",
  DEPLOY_SECRET_STORE_UNAVAILABLE: "CLI_E208",
  DEPLOY_SECRET_FORMAT_INVALID: "CLI_E209",
  DEPLOY_SECRET_LEAKED_IN_ARTIFACT: "CLI_E210",
  DEPLOY_EXECUTE_REQUIRES_CONFIRMATION: "CLI_E211",
  DEPLOY_MANIFEST_MISSING: "CLI_E212",
  DEPLOY_EDGE_RUNTIME_WARNING: "CLI_E213",
  DEPLOY_NOT_IMPLEMENTED: "CLI_E214",
} as const;

export type CLIErrorCode = typeof CLI_ERROR_CODES[keyof typeof CLI_ERROR_CODES];
